CREATE DATABASE BANCO;

USE BANCO;

CREATE TABLE tabela04 (
RP INT,

PROFESSOR VARCHAR(100),

MATÉRIA VARCHAR(100)


);

INSERT into tabela04 (RP,PROFESSOR,MATÉRIA)

values (22300400,"FELIPEMASSA","CORNERS");

INSERT into tabela04 (RP,PROFESSOR,MATÉRIA)

values (22500400,"RUBINHOBARICHELLO","GEARSHIFT");

INSERT into tabela04 (RP,PROFESSOR,MATÉRIA)

values (22100300,"LECLERC","HOWTOCRASH");

INSERT into tabela04 (RP,PROFESSOR,MATÉRIA)

values (22000111,"VERSTAPPEN","MAXMAXMAXMAX");




